# EDA Laptos

## Librerias

In [1]:
import warnings
import pandas as pd
import numpy  as np
import seaborn as sns
import matplotlib.pyplot as plt
# Suppress all warnings
warnings.filterwarnings("ignore")

## Clases

In [2]:
from src.utils import path

## Carga de DataSet

In [41]:
directorio_proyecto = path.obtener_ruta_local()
df = pd.read_csv(directorio_proyecto+'\\data\\raw\\dataset_laptos.csv',delimiter = ',',decimal = ".", encoding='utf-8')

In [42]:
# primeras filas
print("PRIMERAS FILAS DEL DATASET")
display(df.head(5))

print("ÚLTIMAS FILAS DEL DATASET")
display(df.tail(5))

PRIMERAS FILAS DEL DATASET

,Unnamed: 0,link,name,user rating,Price,Sales Package,Model Number,Part Number,Model Name,Series,...,Security Chip,Inbuilt 4G LTE,Cloud Storage,S-video,Dock Port,Firewire Port,RJ11,Read/Write Speed,EMMC Storage Capacity,Optane Memory
0,0,https://www.flipkart.com/asus-rog-strix-scar-1...,ASUS ROG Strix SCAR 17 Core i9 12th Gen - (32 ...,5.0,"?2,34,990","Laptop, Power Adaptor, User Guide, Warranty Do...",G733ZW-LL139WS,90NR08G2-M007S0,G733ZW-LL139WS,ROG Strix SCAR 17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,https://www.flipkart.com/asus-rog-strix-scar-1...,ASUS ROG Strix SCAR 15 Core i9 12th Gen - (32 ...,NaN,"?2,29,990","Laptop, Power Adaptor, User Guide, Warranty Do...",G533ZW-LN136WS,90NR0872-M007L0,G533ZW-LN136WS,ROG Strix SCAR 15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,https://www.flipkart.com/hp-victus-ryzen-7-oct...,HP Victus Ryzen 7 Octa Core 5800H - (16 GB/512...,NaN,"?1,04,091","Laptop, battery, adapter, cables and user manuals",16-e0351AX,552X1PA#ACJ,16-e0351AX,Victus,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,https://www.flipkart.com/lenovo-ideapad-gaming...,Lenovo IdeaPad Gaming 3i Ryzen 7 Octa Core R7-...,NaN,"?87,717","Laptop, Power Adaptor, User Guide, Warranty Do...",15ACH6,82K201RSIN,IdeaPad Gaming 3,IdeaPad Gaming 3i,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,https://www.flipkart.com/lenovo-yoga-slim-7-co...,Lenovo Yoga Slim 7 Core i5 11th Gen - (16 GB/5...,NaN,"?75,990","Laptop, Adaptor",82A300MBIN,1LS2B001653,Yoga Slim 7 14ITL05,Yoga Slim 7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

ÚLTIMAS FILAS DEL DATASET

,Unnamed: 0,link,name,user rating,Price,Sales Package,Model Number,Part Number,Model Name,Series,...,Security Chip,Inbuilt 4G LTE,Cloud Storage,S-video,Dock Port,Firewire Port,RJ11,Read/Write Speed,EMMC Storage Capacity,Optane Memory
979,979,https://www.flipkart.com/nokia-purebook-x14-co...,Nokia PureBook X14 Core i5 10th Gen - (8 GB/51...,4.4,"?53,990","Laptop, Power Adaptor, User Guide with Warrant...",NKi510UL85S,NKi510UL85S,NaN,PureBook X14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
980,980,https://www.flipkart.com/hp-spectre-folio-core...,HP Spectre Folio Core i7 10th Gen - (16 GB/512...,NaN,"?2,39,759","Laptop, Power Adaptor, User Guide, Warranty Do...",13-ak1004TU,3P296PA,NaN,Spectre Folio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
981,981,https://www.flipkart.com/hp-envy-x360-ryzen-5-...,HP Envy x360 Ryzen 5 Hexa Core 4500U - (8 GB/5...,NaN,"?85,555","Laptop, Power Adaptor, User Guide, Warranty Do...",13-ay0078AU,17J58PA,NaN,Envy x360,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
982,982,https://www.flipkart.com/hp-14a-celeron-dual-c...,HP 14a Celeron Dual Core - (4 GB/64 GB EMMC St...,3.6,"?26,990","Laptop, Power Adaptor, User Guide, Warranty Do...",14a- na0002TU,2Z326PA,NaN,14a,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64 GB,NaN
983,983,https://www.flipkart.com/lenovo-core-i3-10th-g...,Lenovo Core i3 10th Gen - (4 GB/1 TB HDD/Windo...,3.1,"?44,590","Laptop, Power Adaptor, User Guide, Warranty Do...",V14,82C4A00LIH,NaN,NaN,...,TPM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df = df[['name', 'Sales Package', 'Color','Type','Suitable For','Processor Brand','Processor Name','SSD Capacity','RAM','RAM Type','Graphic Processor','Operating System']]

In [44]:
# Dimensiones del dataset
print("DIMENSIONES DEL DATASET")
print(f"Número de filas: {df.shape[0]}")
print(f"Número de columnas: {df.shape[1]}")

# Información general
print("INFORMACIÓN GENERAL")
df.info()

DIMENSIONES DEL DATASET
Número de filas: 984
Número de columnas: 12
INFORMACIÓN GENERAL
<class 'pandas.DataFrame'>
RangeIndex: 984 entries, 0 to 983
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               984 non-null    str
 1   Sales Package      984 non-null    str
 2   Color              984 non-null    str
 3   Type               984 non-null    str
 4   Suitable For       984 non-null    str
 5   Processor Brand    984 non-null    str
 6   Processor Name     984 non-null    str
 7   SSD Capacity       876 non-null    str
 8   RAM                984 non-null    str
 9   RAM Type           984 non-null    str
 10  Graphic Processor  964 non-null    str
 11  Operating System   984 non-null    str
dtypes: str(12)
memory usage: 92.4 KB

In [45]:
# Tipos de datos
print("TIPOS DE DATOS")
print(df.dtypes)

TIPOS DE DATOS
name                 str
Sales Package        str
Color                str
Type                 str
Suitable For         str
Processor Brand      str
Processor Name       str
SSD Capacity         str
RAM                  str
RAM Type             str
Graphic Processor    str
Operating System     str
dtype: object

In [46]:
# Estadísticas descriptivas de variables numéricas
print("ESTADÍSTICAS DESCRIPTIVAS - VARIABLES NUMÉRICAS")
display(df.describe().T)

# Estadísticas adicionales
print("ESTADÍSTICAS ADICIONALES")
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
for col in numeric_cols:
    print(f"\n{col}:")
    print(f"  Media: {df[col].mean():.2f}")
    print(f"  Mediana: {df[col].median():.2f}")
    print(f"  Moda: {df[col].mode().values[0] if len(df[col].mode()) > 0 else 'N/A'}")
    print(f"  Desviación estándar: {df[col].std():.2f}")
    print(f"  Varianza: {df[col].var():.2f}")
    print(f"  Asimetría (Skewness): {df[col].skew():.2f}")
    print(f"  Curtosis (Kurtosis): {df[col].kurtosis():.2f}")

ESTADÍSTICAS DESCRIPTIVAS - VARIABLES NUMÉRICAS

,count,unique,top,freq
name,984,943,ASUS ROG Strix SCAR 17 Core i9 12th Gen - (32 ...,2
Sales Package,984,106,"Laptop, Power Adaptor, User Guide, Warranty Do...",411
Color,984,132,Black,101
Type,984,9,Thin and Light Laptop,503
Suitable For,984,52,Processing & Multitasking,535
Processor Brand,984,5,Intel,700
Processor Name,984,30,Core i5,298
SSD Capacity,876,5,512 GB,510
RAM,984,4,8 GB,557
RAM Type,984,8,DDR4,855
Graphic Processor,964,151,Intel Integrated UHD,192
Operating System,984,10,Windows 10 Home,438

ESTADÍSTICAS ADICIONALES

In [47]:
# Estadísticas de variables categóricas
print("ESTADÍSTICAS DESCRIPTIVAS - VARIABLES CATEGÓRICAS")

categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    print(f"\n{col}:")
    print(f"  Valores únicos: {df[col].nunique()}")
    print(f"  Valor más frecuente: {df[col].mode().values[0] if len(df[col].mode()) > 0 else 'N/A'}")
    print(f"  Top 5 valores:")
    print(df[col].value_counts().head())

ESTADÍSTICAS DESCRIPTIVAS - VARIABLES CATEGÓRICAS

name:
  Valores únicos: 943
  Valor más frecuente: ASUS Core i5 11th Gen - (16 GB/512 GB SSD/Windows 11 Home) UX363EA-HP562WS Thin and Light Laptop  (13.3 Inch, Pine Grey, 1.30 Kg, With MS Office)
  Top 5 valores:
name
ASUS ROG Strix SCAR 17 Core i9 12th Gen - (32 GB/1 TB SSD/Windows 11 Home/8 GB Graphics/NVIDIA GeForce RTX 3070 Ti) G733ZW-LL139WS Gaming Laptop  (17.3 inch, Off Black, 2.90 kg, With MS Office)                  2
ASUS ROG Strix SCAR 15 Core i9 12th Gen - (32 GB/1 TB SSD/Windows 11 Home/8 GB Graphics/NVIDIA GeForce RTX 3070 Ti) G533ZW-LN136WS Gaming Laptop  (15.6 inch, Off Black, 2.30 kg, With MS Office)                  2
HP Victus Ryzen 7 Octa Core 5800H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 3050) 16-e0351AX Gaming Laptop  (16.1 inch, Mica Silver, 2.48 kg, With MS Office)                           2
Lenovo IdeaPad Gaming 3i Ryzen 7 Octa Core R7-5800H 5th Gen - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 3050) 15ACH6 Gaming Laptop  (15.6 inch, Shadow Black, 2.25 kg, With MS Office)    2
Lenovo Yoga Slim 7 Core i5 11th Gen - (16 GB/512 GB SSD/Windows 11 Home) 82A300MBIN Thin and Light Laptop  (14 inch, Slate Grey, With MS Office)                                                                   2
Name: count, dtype: int64

Sales Package:
  Valores únicos: 106
  Valor más frecuente: Laptop, Power Adaptor, User Guide, Warranty Documents
  Top 5 valores:
Sales Package
Laptop, Power Adaptor, User Guide, Warranty Documents    411
Laptop, battery, adapter, cables and user manuals        127
Laptop, Battery, Adapter, Cables and User Manuals         69
Laptop, Power Adaptor, User Guide                         53
Laptop, Power Adapter, User Guide, Warranty Documents     33
Name: count, dtype: int64

Color:
  Valores únicos: 132
  Valor más frecuente: Black
  Top 5 valores:
Color
Black                 101
Transparent Silver     80
Natural Silver         71
Platinum Silver        49
Silver                 38
Name: count, dtype: int64

Type:
  Valores únicos: 9
  Valor más frecuente: Thin and Light Laptop
  Top 5 valores:
Type
Thin and Light Laptop    503
Gaming Laptop            222
Laptop                   135
2 in 1 Laptop             64
Notebook                  25
Name: count, dtype: int64

Suitable For:
  Valores únicos: 52
  Valor más frecuente: Processing & Multitasking
  Top 5 valores:
Suitable For
Processing & Multitasking                  535
Gaming                                     115
Everyday Use                                86
Gaming, Processing & Multitasking           68
Everyday Use, Processing & Multitasking     48
Name: count, dtype: int64

Processor Brand:
  Valores únicos: 5
  Valor más frecuente: Intel
  Top 5 valores:
Processor Brand
Intel       700
AMD         268
Apple        12
Qualcomm      2
MediaTek      2
Name: count, dtype: int64

Processor Name:
  Valores únicos: 30
  Valor más frecuente: Core i5
  Top 5 valores:
Processor Name
Core i5              298
Core i3              216
Core i7              116
Ryzen 5 Hexa Core     89
Ryzen 7 Octa Core     72
Name: count, dtype: int64

SSD Capacity:
  Valores únicos: 5
  Valor más frecuente: 512 GB
  Top 5 valores:
SSD Capacity
512 GB    510
256 GB    226
1 TB      130
128 GB      7
2 TB        3
Name: count, dtype: int64

RAM:
  Valores únicos: 4
  Valor más frecuente: 8 GB
  Top 5 valores:
RAM
8 GB     557
16 GB    306
4 GB     106
32 GB     15
Name: count, dtype: int64

RAM Type:
  Valores únicos: 8
  Valor más frecuente: DDR4
  Top 5 valores:
RAM Type
DDR4       855
LPDDR4X     86
DDR5        21
LPDDR4      14
LPDDR5       4
Name: count, dtype: int64

Graphic Processor:
  Valores únicos: 151
  Valor más frecuente: Intel Integrated UHD
  Top 5 valores:
Graphic Processor
Intel Integrated UHD        192
Intel Integrated Iris Xe    118
NVIDIA GeForce GTX 1650      57
NVIDIA GeForce RTX 3050      47
AMD Radeon AMD               37
Name: count, dtype: int64

Operating System:
  Valores únicos: 10
  Valor más frecuente: Windows 10 Home
  Top 5 valores:
Operating System
Windows 10 Home    438
Windows 11 Home    394
Windows 10          94
Chrome              17
Windows 10 Pro      17
Name: count, dtype: int64

In [48]:
# Análisis de duplicados
print("ANÁLISIS DE VALORES DUPLICADOS")
print(f"Número de filas duplicadas: {df.duplicated().sum()}")
print(f"Porcentaje de duplicados: {(df.duplicated().sum() / len(df)) * 100:.2f}%")

if df.duplicated().sum() > 0:
    print("\nFilas duplicadas:")
    display(df[df.duplicated(keep=False)].sort_values(by=df.columns.tolist()))

ANÁLISIS DE VALORES DUPLICADOS
Número de filas duplicadas: 40
Porcentaje de duplicados: 4.07%

Filas duplicadas:

,name,Sales Package,Color,Type,Suitable For,Processor Brand,Processor Name,SSD Capacity,RAM,RAM Type,Graphic Processor,Operating System
237,ASUS Core i5 11th Gen - (16 GB/512 GB SSD/Wind...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Pine Grey,Thin and Light Laptop,Processing & Multitasking,Intel,Core i5,512 GB,16 GB,LPDDR4X,Intel Integrated Iris Xe Graphics,Windows 11 Home
247,ASUS Core i5 11th Gen - (16 GB/512 GB SSD/Wind...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Pine Grey,Thin and Light Laptop,Processing & Multitasking,Intel,Core i5,512 GB,16 GB,LPDDR4X,Intel Integrated Iris Xe Graphics,Windows 11 Home
15,ASUS ROG Flow X13 (2021) Ryzen 9 Octa Core Ryz...,"Laptop, Power Adaptor, User Guide, GV 301 Slee...",Black,2 in 1 Gaming Laptop,"Gaming, Processing & Multitasking",AMD,Ryzen 9 Octa Core,1 TB,32 GB,LPDDR4X,NVIDIA GeForce GTX 1650,Windows 10 Home
87,ASUS ROG Flow X13 (2021) Ryzen 9 Octa Core Ryz...,"Laptop, Power Adaptor, User Guide, GV 301 Slee...",Black,2 in 1 Gaming Laptop,"Gaming, Processing & Multitasking",AMD,Ryzen 9 Octa Core,1 TB,32 GB,LPDDR4X,NVIDIA GeForce GTX 1650,Windows 10 Home
666,ASUS ROG Strix G15 (2021) Ryzen 7 Octa Core 48...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Eclipse Gray,Gaming Laptop,"Gaming, Processing & Multitasking",AMD,Ryzen 7 Octa Core,512 GB,8 GB,DDR4,NVIDIA GeForce GTX 1650,Windows 10 Home
...,...,...,...,...,...,...,...,...,...,...,...,...
92,realme Book Prime Core i5 11th Gen - (16 GB/51...,"Laptop, Power Adaptor, Battery, Warranty Docum...",Blue,Thin and Light Laptop,"Entertainment, Performance, Processing & Multi...",Intel,Core i5,512 GB,16 GB,LPDDR4X,Intel Integrated Iris Xe,Windows 11 Home
19,realme Book Prime Core i5 11th Gen - (16 GB/51...,"Laptop, Power Adaptor, Battery, Warranty Docum...",Green,Thin and Light Laptop,"Entertainment, Performance, Processing & Multi...",Intel,Core i5,512 GB,16 GB,LPDDR4X,Intel Integrated Iris Xe,Windows 11 Home
91,realme Book Prime Core i5 11th Gen - (16 GB/51...,"Laptop, Power Adaptor, Battery, Warranty Docum...",Green,Thin and Light Laptop,"Entertainment, Performance, Processing & Multi...",Intel,Core i5,512 GB,16 GB,LPDDR4X,Intel Integrated Iris Xe,Windows 11 Home
18,realme Book Prime Core i5 11th Gen - (16 GB/51...,"Laptop, Power Adaptor, Battery, Warranty Docum...",Grey,Thin and Light Laptop,"Entertainment, Performance, Processing & Multi...",Intel,Core i5,512 GB,16 GB,LPDDR4X,Intel Integrated Iris Xe,Windows 11 Home
90,realme Book Prime Core i5 11th Gen - (16 GB/51...,"Laptop, Power Adaptor, Battery, Warranty Docum...",Grey,Thin and Light Laptop,"Entertainment, Performance, Processing & Multi...",Intel,Core i5,512 GB,16 GB,LPDDR4X,Intel Integrated Iris Xe,Windows 11 Home

In [50]:
# Análisis de nulos
print("ANÁLISIS DE VALORES NULOS")
print(f"Total de valores nulos: {df.isnull().sum().sum()}")
print(f"Porcentaje de nulos sobre el total: {(df.isnull().sum().sum() / df.size) * 100:.2f}%")

print("\nNulos por columna:")
nulos_por_col = df.isnull().sum()
porcentaje_por_col = (df.isnull().sum() / len(df)) * 100
resumen_nulos = pd.DataFrame({
    'Nulos': nulos_por_col,
    'Porcentaje': porcentaje_por_col.map('{:.2f}%'.format)
})
display(resumen_nulos[resumen_nulos['Nulos'] > 0])

if df.isnull().sum().sum() > 0:
    print("\nFilas con al menos un nulo:")
    display(df[df.isnull().any(axis=1)])

ANÁLISIS DE VALORES NULOS
Total de valores nulos: 128
Porcentaje de nulos sobre el total: 1.08%

Nulos por columna:

                   Nulos Porcentaje
SSD Capacity         108     10.98%
Graphic Processor     20      2.03%

Filas con al menos un nulo:

,name,Sales Package,Color,Type,Suitable For,Processor Brand,Processor Name,SSD Capacity,RAM,RAM Type,Graphic Processor,Operating System
50,ASUS VivoBook 15 Core i3 10th Gen - (8 GB/1 TB...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Transparent Silver,Thin and Light Laptop,Processing & Multitasking,Intel,Core i3,NaN,8 GB,DDR4,Intel Integrated UHD,Windows 11 Home
101,ASUS VivoBook 15 (2021) Core i5 10th Gen - (8 ...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Transparent Silver,Thin and Light Laptop,Processing & Multitasking,Intel,Core i5,NaN,8 GB,DDR4,Intel Integrated UHD,Windows 11 Home
111,ASUS VivoBook 15 (2021) Core i3 11th Gen - (8 ...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Slate Grey,Thin and Light Laptop,Processing & Multitasking,Intel,Core i3,NaN,8 GB,DDR4,Intel Integrated UHD,Windows 11 Home
115,HP Chromebook Celeron Quad Core - (4 GB/64 GB ...,"Laptop, Power Adapter, User Guide, Warranty Do...",Forest Teal,Thin and Light Laptop,Processing & Multitasking,Intel,Celeron Quad Core,NaN,4 GB,LPDDR4,Intel Integrated UHD Graphics,Chrome
116,HP Chromebook Celeron Dual Core - (4 GB/64 GB ...,"Laptop, Power Adapter, User Guide, Warranty Do...",Mineral Silver,Thin and Light Laptop,Processing & Multitasking,Intel,Celeron Dual Core,NaN,4 GB,LPDDR4,Intel Integrated UHD Graphics,Chrome
...,...,...,...,...,...,...,...,...,...,...,...,...
968,Lenovo Ideapad S145 Core i3 7th Gen - (4 GB/1 ...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Platinum Grey,Thin and Light Laptop,Processing & Multitasking,Intel,Core i3,NaN,4 GB,DDR4,Intel Integrated HD 620,Windows 10 Home
971,HP 250 Core i5 10th Gen - (8 GB/1 TB HDD/Windo...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Grey,Business Laptop,Everyday Use,Intel,Core i5,NaN,8 GB,DDR4,Intel Integrated,Windows 10
972,Lenovo Core i5 8th Gen - (4 GB/1 TB HDD/DOS) V...,"Laptop, Power Adaptor, User Guide",Grey,Thin and Light Laptop,Processing & Multitasking,Intel,Core i5,NaN,4 GB,DDR4,Intel Integrated Intel UHD Graphics 620,DOS
982,HP 14a Celeron Dual Core - (4 GB/64 GB EMMC St...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Ceramic White,Chromebook,Processing & Multitasking,Intel,Celeron Dual Core,NaN,4 GB,DDR4,Intel Integrated UHD 605,Chrome
983,Lenovo Core i3 10th Gen - (4 GB/1 TB HDD/Windo...,"Laptop, Power Adaptor, User Guide, Warranty Do...",Black,Laptop,Processing & Multitasking,Intel,Core i3,NaN,4 GB,DDR4,AMD Radeon R4,Windows 10 Pro

In [51]:
df = df[['name', 'Sales Package', 'Color','Type','Suitable For','Processor Brand','Processor Name','RAM','RAM Type','Operating System']]

In [53]:
# Boxplots para detectar outliers
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

if len(numeric_cols) > 0:
    n_cols = 3
    n_rows = (len(numeric_cols) + n_cols - 1) // n_cols

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(15, 5*n_rows))
    axes = axes.flatten() if len(numeric_cols) > 1 else [axes]

    for idx, col in enumerate(numeric_cols):
        axes[idx].boxplot(df[col].dropna(), vert=True)
        axes[idx].set_title(f'Boxplot de {col}', fontweight='bold')
        axes[idx].set_ylabel(col)
        axes[idx].grid(alpha=0.3)

    # Ocultar ejes vacíos
    for idx in range(len(numeric_cols), len(axes)):
        axes[idx].set_visible(False)

    plt.tight_layout()
    plt.show()